# Welcome to The Doldrums
This is a work in progress website


-------------------------------------------------------------------------------------------

#██████╗░░█████╗░██╗░░░░░██████╗░██████╗░██╗░░░██╗███╗░░░███╗░██████╗
#██╔══██╗██╔══██╗██║░░░░░██╔══██╗██╔══██╗██║░░░██║████╗░████║██╔════╝
#██║░░██║██║░░██║██║░░░░░██║░░██║██████╔╝██║░░░██║██╔████╔██║╚█████╗░
#██║░░██║██║░░██║██║░░░░░██║░░██║██╔══██╗██║░░░██║██║╚██╔╝██║░╚═══██╗
#██████╔╝╚█████╔╝███████╗██████╔╝██║░░██║╚██████╔╝██║░╚═╝░██║██████╔╝
#╚═════╝░░╚════╝░╚══════╝╚═════╝░╚═╝░░╚═╝░╚═════╝░╚═╝░░░░░╚═╝╚═════╝░


-------------------------------------------------------------------------------------------
